### UPDATE USER PHONE
PATCH  http://localhost:8080/api/v1/users/me/phone
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWU4MmRmZDktMWZjOC00NWM0LTlhMTgtOGI1ZDEwMmJlM2U3Iiwicm9sZSI6IkNVU1RPTUVSIiwic3ViIjoiOWU4MmRmZDktMWZjOC00NWM0LTlhMTgtOGI1ZDEwMmJlM2U3IiwiZXhwIjoxNzg2Nzc5NjU1LCJpYXQiOjE3ODY2OTMyNTV9.HbPlzelpi-SERjtfVchGL1xMwnm3tvgBhV58dtRMf0w
Content-Type: application/json

{
    "new_phone": "089603594916"
}